# Generated by Django 5.1.2 on 2024-11-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.TextField()),
                ('cname', models.TextField()),
                ('disc', models.TextField()),
                ('price', models.IntegerField()),
                ('img', models.FileField(upload_to='')),
            ],
        ),
    ]
